repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ['-i']
        files: '\.(c|h)$'
        exclude: '^reference/sylves-src/'
      - id: cppcheck
        args: ['--enable=warning,style,performance,portability', '--inline-suppr', '--quiet']
        files: '\.(c|h)$'
        exclude: '^reference/sylves-src/'

  - repo: local
    hooks:
      - id: check-header-guards
        name: Check header guards
        entry: python scripts/check_header_guards.py
        language: python
        files: '\.h$'
        exclude: '^reference/sylves-src/'
        
      - id: check-copyright
        name: Check copyright headers
        entry: python scripts/check_copyright.py
        language: python
        files: '\.(c|h)$'
        exclude: '^reference/sylves-src/'
